import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const url = process.env.DATABASE_URL ?? "file:./prisma/dev.db";
const adapter = new PrismaBetterSqlite3({ url });
const prisma = new PrismaClient({ adapter });

const products = [
  // ── Multivitamins ────────────────────────────────────────────────────────────
  {
    name: "Maxi Health Supreme®",
    slug: "maxi-health-supreme",
    description: "The most complete, well-balanced multi-vitamin/mineral supplement. An ideal foundation for a personal nutritional program. 90 capsules.",
    descriptionHe: "תוסף המולטי-ויטמין המלא והמאוזן ביותר. בסיס אידיאלי לתוכנית תזונה אישית. 90 כמוסות.",
    price: 82.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/MH6_MAIN_e78802ce-fff8-4bda-8877-261c8ad8bb89.jpg",
    category: "Multivitamins",
    stock: 120,
    isNew: true,
  },
  {
    name: "Maxi Health Two Complete™",
    slug: "maxi-health-two-complete",
    description: "A well-balanced, just 2-a-day multi-vitamin combining essential vitamins and minerals in a synergistic blend. 60 capsules.",
    descriptionHe: "מולטי-ויטמין מאוזן בנטילה של 2 כמוסות ביום בלבד. שילוב סינרגטי של ויטמינים ומינרלים חיוניים. 60 כמוסות.",
    price: 94.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/86b0fd0b3aca7990359f72d5d9d95beb.jpg",
    category: "Multivitamins",
    stock: 150,
  },
  {
    name: "Maxivite Complete™ with Iron",
    slug: "maxivite-complete-with-iron",
    description: "Complete multivitamin/mineral formula with iron. Supports overall daily nutrition. 90 tablets.",
    descriptionHe: "פורמולת מולטי-ויטמין ומינרלים מלאה עם ברזל. תומכת בתזונה יומיומית מאוזנת. 90 טבליות.",
    price: 116.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/MVC_MAIN_45137122-dffa-472f-8f6f-2f4608286963.jpg",
    category: "Multivitamins",
    stock: 100,
  },
  // ── Vitamin C ────────────────────────────────────────────────────────────────
  {
    name: "Max C 1000™",
    slug: "max-c-1000",
    description: "High-potency 1000mg Vitamin C for immune support and antioxidant protection. Gluten free, Non GMO. 90 tablets.",
    descriptionHe: "ויטמין C בעוצמה גבוהה — 1000 מ\"ג לחיזוק מערכת החיסון והגנה נוגדת חמצון. ללא גלוטן, ללא GMO. 90 טבליות.",
    price: 71.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/C11_MAIN_ae8d1542-cfbd-4f8d-bfb7-d75a31dfd486.jpg",
    category: "Vitamins",
    stock: 180,
    isNew: true,
  },
  {
    name: "Vitamin C 500™",
    slug: "vitamin-c-500",
    description: "500mg Vitamin C from tapioca. A gentle, corn-free formula for daily antioxidant and immune support. 100 tablets.",
    descriptionHe: "500 מ\"ג ויטמין C ממקור טפיוקה. פורמולה עדינה ללא תירס לתמיכה יומיומית במערכת החיסון. 100 טבליות.",
    price: 74.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/CT_MAIN.png",
    category: "Vitamins",
    stock: 160,
  },
  {
    name: "Vitamin C! Gummies™",
    slug: "vitamin-c-gummies",
    description: "Delicious chewable Vitamin C gummies. A fun and tasty way for the whole family to get their daily vitamin C. 60 gummies.",
    descriptionHe: "סוכריות גומי טעימות עם ויטמין C. דרך כיפית וטעימה לכל המשפחה לקבל את מנת ויטמין C היומית. 60 גומי.",
    price: 74.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/CLG_MAINwithgummies_ae271b7a-e179-4b5e-a7c4-5148c6816563.jpg",
    category: "Vitamins",
    stock: 200,
  },
  // ── Vitamin D3 ───────────────────────────────────────────────────────────────
  {
    name: "Vegan D3 5000™",
    slug: "vegan-d3-5000",
    description: "5000 IU vegan Vitamin D3 from lichen. Supports bone health, immune function, and mood. Non GMO, Gluten Free. 90 capsules.",
    descriptionHe: "5000 יחב\"ל ויטמין D3 טבעוני ממקור כמוסות. תומך בבריאות העצמות, מערכת החיסון ומצב הרוח. ללא GMO, ללא גלוטן. 90 כמוסות.",
    price: 74.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/VD5_MAIN_8f85f8e3-94bd-4009-b380-e935a47c2e3b.jpg",
    category: "Vitamins",
    stock: 140,
  },
  {
    name: "Vegan D3 and K2™",
    slug: "vegan-d3-and-k2",
    description: "5000 IU Vegan D3 combined with Vitamin K2 (MK-7) for optimal calcium absorption and cardiovascular health. 90 capsules.",
    descriptionHe: "5000 יחב\"ל ויטמין D3 טבעוני בשילוב ויטמין K2 (MK-7) לספיגת סידן מיטבית ובריאות הלב. 90 כמוסות.",
    price: 144.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/VDK_MAIN_fe92e5e9-eb2c-4f69-a221-7dfe9a7729b5.png",
    category: "Vitamins",
    stock: 110,
  },
  {
    name: "Maxi D3 10,000™",
    slug: "maxi-d3-10000",
    description: "High-potency 10,000 IU Vitamin D3 for those requiring therapeutic support. 90 softgels.",
    descriptionHe: "ויטמין D3 בעוצמה גבוהה של 10,000 יחב\"ל למי שזקוק לתמיכה טיפולית. 90 כמוסות רכות.",
    price: 71.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/MH594-90-MaxiD310_000-MAIN.png",
    category: "Vitamins",
    stock: 90,
  },
  // ── B Vitamins ───────────────────────────────────────────────────────────────
  {
    name: "B-12 Lozenges™",
    slug: "b-12-lozenges",
    description: "Methylcobalamin B12 lozenges for fast absorption. Supports energy, nerve function, and red blood cell production. 90 lozenges.",
    descriptionHe: "כדורי מציצה עם B12 מתילקובלמין לספיגה מהירה. תומך באנרגיה, תפקוד עצבי וייצור כדוריות דם אדומות. 90 כדורי מציצה.",
    price: 82.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/B129_MAIN_424d33c0-db64-4261-b721-c7bcfa8edae4.jpg",
    category: "B Vitamins",
    stock: 130,
  },
  {
    name: "Methyl B12 Lozenges 1000™",
    slug: "methyl-b12-lozenges-1000",
    description: "1000mcg Methylcobalamin B12 lozenges. Bioavailable form for superior absorption. Gluten free, Non GMO. 90 lozenges.",
    descriptionHe: "כדורי מציצה עם 1000 מק\"ג B12 מתילקובלמין. צורה ביו-זמינה לספיגה מעולה. ללא גלוטן, ללא GMO. 90 כדורי מציצה.",
    price: 44.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/B16_Main_9c2f44a1-28e7-4b44-87b7-aa6be82b9885.jpg",
    category: "B Vitamins",
    stock: 150,
  },
  {
    name: "Liquid B Complex™",
    slug: "liquid-b-complex",
    description: "Full spectrum liquid B-vitamin complex. Alcohol free, easily absorbed. Supports energy metabolism and nervous system. 8 fl oz.",
    descriptionHe: "קומפלקס ויטמיני B נוזלי בספקטרום מלא. ללא אלכוהול, נספג בקלות. תומך במטבוליזם האנרגיה ובמערכת העצבים. 240 מ\"ל.",
    price: 99.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/BL_MAIN_153173b5-f82a-46bd-9bdc-f4046abbbc72.jpg",
    category: "B Vitamins",
    stock: 80,
  },
  {
    name: "Maxi B-6™",
    slug: "maxi-b-6",
    description: "50mg Vitamin B6 (Pyridoxine HCl). Supports amino acid metabolism, brain health, and PMS relief. 100 tablets.",
    descriptionHe: "50 מ\"ג ויטמין B6 (פירידוקסין). תומך במטבוליזם חומצות אמינו, בריאות המוח והקלה על תסמיני PMS. 100 טבליות.",
    price: 35.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/B6_MAIN_cdb81b2b-bbe3-4c73-8a83-f976df8e1384.jpg",
    category: "B Vitamins",
    stock: 200,
  },
  // ── Minerals ─────────────────────────────────────────────────────────────────
  {
    name: "Maxi Magnesium Citrate™",
    slug: "maxi-magnesium-citrate",
    description: "Highly bioavailable magnesium citrate for muscle relaxation, sleep quality, and stress relief. Gluten Free. 90 capsules.",
    descriptionHe: "מגנזיום ציטרט בזמינות ביולוגית גבוהה להרפיית שרירים, שיפור השינה והפחתת מתח. ללא גלוטן. 90 כמוסות.",
    price: 66.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/MCT_MAIN_229a44e8-97c0-4716-a601-3e86e3072089.jpg",
    category: "Minerals",
    stock: 140,
  },
  {
    name: "Maxi Magnesium Theanine Gummies™",
    slug: "maxi-magnesium-theanine-gummies",
    description: "Magnesium plus L-Theanine gummies for relaxation and stress relief without drowsiness. 60 gummies.",
    descriptionHe: "סוכריות גומי עם מגנזיום ו-L-תיאנין להרפיה והפחתת מתח ללא עייפות. 60 גומי.",
    price: 82.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/MT_MAIN.png",
    category: "Minerals",
    stock: 120,
    isNew: true,
  },
  {
    name: "CAL M D™",
    slug: "cal-m-d",
    description: "Calcium, Magnesium, and Vitamin D3 in one formula. Optimal bone support with enhanced absorption. 90 capsules.",
    descriptionHe: "סידן, מגנזיום וויטמין D3 בפורמולה אחת לתמיכה מיטבית בעצמות עם ספיגה משופרת. 90 כמוסות.",
    price: 107.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/CK_MAIN_ac1811b6-f700-422e-9063-33ef0bdeb393.png",
    category: "Minerals",
    stock: 110,
  },
  {
    name: "Calcium-D3 Gummies™",
    slug: "calcium-d3-gummies",
    description: "Chewable calcium gummies with Vitamin D3. A delicious way to support bone health for the whole family. 60 gummies.",
    descriptionHe: "סוכריות גומי לעיסות עם סידן וויטמין D3. דרך טעימה לתמוך בבריאות העצמות לכל המשפחה. 60 גומי.",
    price: 74.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/CALG_MAIN_984aeb95-3c22-428d-868a-c6a0f7f500e2.jpg",
    category: "Minerals",
    stock: 160,
  },
  {
    name: "Maxi Liquid Iron™",
    slug: "maxi-liquid-iron",
    description: "Gentle liquid iron formula with Vitamin C for enhanced absorption. Non-constipating. Gluten free, Vegetarian. 8 fl oz.",
    descriptionHe: "פורמולת ברזל נוזלית עדינה עם ויטמין C לספיגה משופרת. לא גורמת לעצירות. ללא גלוטן, צמחוני. 240 מ\"ל.",
    price: 107.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/LI_MAIN_203be4ad-f35f-41be-b329-2c6b38872274.jpg",
    category: "Minerals",
    stock: 90,
  },
  // ── Omega ────────────────────────────────────────────────────────────────────
  {
    name: "Omega-3 Max™",
    slug: "omega-3-max",
    description: "High-concentration EPA & DHA from purified deep-sea fish oil. Supports heart, brain, and joint health. 90 softgels.",
    descriptionHe: "ריכוז גבוה של EPA ו-DHA משמן דגי ים עמוק מזוקק. תומך בבריאות הלב, המוח והמפרקים. 90 כמוסות רכות.",
    price: 140.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/Omega_3_Max_-_90_-MAIN.png",
    category: "Omega",
    stock: 100,
    isNew: true,
  },
  {
    name: "Chewable Omega Yums 1000™",
    slug: "chewable-omega-yums-1000",
    description: "1000mg chewable omega-3 gummies with natural fruit flavor. Great for children and adults who dislike swallowing softgels. 90 gummies.",
    descriptionHe: "1000 מ\"ג גומי אומגה-3 לעיסות בטעם פירות טבעי. מצוין לילדים ומבוגרים שמתקשים לבלוע כמוסות. 90 גומי.",
    price: 127.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/YT1_MAIN.png",
    category: "Omega",
    stock: 110,
  },
  {
    name: "Focus & Calm DHA™",
    slug: "focus-calm-dha",
    description: "High-DHA formula supporting brain development, focus, and cognitive calm. Ideal for children and adults. 90 softgels.",
    descriptionHe: "פורמולה עשירה ב-DHA לתמיכה בהתפתחות המוח, ריכוז ורוגע קוגניטיבי. מתאים לילדים ומבוגרים. 90 כמוסות רכות.",
    price: 185.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/DHA_MAIN.png",
    category: "Omega",
    stock: 80,
  },
  // ── Digestive / Probiotics ───────────────────────────────────────────────────
  {
    name: "Maxi Active Pro 10™",
    slug: "maxi-active-pro-10",
    description: "10 billion CFU probiotic with 10 strains. Chewable, great-tasting formula for digestive balance and immune support. 90 chewables.",
    descriptionHe: "פרוביוטיקה עם 10 מיליארד יחידות ו-10 זנים. פורמולה לעיסה בטעם נעים לאיזון מערכת העיכול וחיזוק החיסון. 90 לעיסות.",
    price: 149.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/C10_MAIN-_shop.jpg",
    category: "Digestive",
    stock: 90,
  },
  {
    name: "Maxi Active Pro 50™",
    slug: "maxi-active-pro-50",
    description: "50 billion CFU professional-strength probiotic. 10 diverse strains for comprehensive gut microbiome support. 60 capsules.",
    descriptionHe: "פרוביוטיקה בעוצמה מקצועית עם 50 מיליארד יחידות ו-10 זנים מגוונים לתמיכה מקיפה במיקרוביום. 60 כמוסות.",
    price: 177.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/50_MAIN_1d8abb10-96a0-4ba7-93fb-c834c568aa84.jpg",
    category: "Digestive",
    stock: 70,
  },
  {
    name: "Fibermax Supreme™",
    slug: "fibermax-supreme",
    description: "Premium psyllium husk fiber blend for digestive regularity, cholesterol support, and healthy blood sugar. 180 capsules.",
    descriptionHe: "תערובת סיבים מקליפת פסיליום לקביעות מערכת העיכול, תמיכה בכולסטרול ורמות סוכר תקינות. 180 כמוסות.",
    price: 99.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/QFXS_MAIN_30a2c377-f1fe-4b00-929c-4bdeeb054199.jpg",
    category: "Digestive",
    stock: 110,
  },
  // ── Sleep ────────────────────────────────────────────────────────────────────
  {
    name: "Maxi Melatonin™ 5 mg",
    slug: "maxi-melatonin-5mg",
    description: "5mg melatonin to support healthy sleep cycles and ease jet lag. Fast-release formula. 90 capsules.",
    descriptionHe: "5 מ\"ג מלטונין לתמיכה במחזור שינה בריא והקלה על ג'ט לג. פורמולה לשחרור מהיר. 90 כמוסות.",
    price: 71.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/M5_MAIN_2252e3e7-8ade-477a-b781-48f92b4c10b7.jpg",
    category: "Sleep",
    stock: 160,
  },
  {
    name: "Mel O Chew™ Melatonin",
    slug: "mel-o-chew-melatonin",
    description: "Chewable melatonin in a pleasant cherry flavor. Great for those who prefer not to swallow capsules. Available in 1, 3, 5, and 10 mg.",
    descriptionHe: "מלטונין לעיסה בטעם דובדבן נעים. מצוין למי שמעדיף לא לבלוע כמוסות. זמין ב-1, 3, 5 ו-10 מ\"ג.",
    price: 49.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/MC_100.jpg",
    category: "Sleep",
    stock: 180,
  },
  // ── Energy & Fitness ─────────────────────────────────────────────────────────
  {
    name: "Creatine Monohydrate™",
    slug: "creatine-monohydrate",
    description: "Pure micronized creatine monohydrate to support muscle strength, power output, and exercise performance. 300g powder.",
    descriptionHe: "קריאטין מונוהידרט מיקרוניזד טהור לתמיכה בכוח שרירים, עוצמה ורמת ביצוע גופנית. אבקה 300 גרם.",
    price: 152.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/CC1.jpg",
    category: "Energy & Fitness",
    stock: 80,
    isNew: true,
  },
  {
    name: "Berberine CaloriBurn®",
    slug: "berberine-caloriburn",
    description: "Berberine HCl with green tea extract for healthy blood sugar, metabolism, and weight management. 90 capsules.",
    descriptionHe: "ברברין HCl עם תמצית תה ירוק לרמות סוכר בריאות, מטבוליזם ואיזון משקל. 90 כמוסות.",
    price: 157.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/BER_MAIN.png",
    category: "Energy & Fitness",
    stock: 70,
  },
  {
    name: "Maxi Green Energee™",
    slug: "maxi-green-energee",
    description: "Greens powder capsules with spirulina, chlorella, and antioxidant-rich superfoods. Natural energy without caffeine. 90 capsules.",
    descriptionHe: "כמוסות אבקת ירוקים עם ספירולינה, כלורלה וסופרפודס עשירים בנוגדי חמצון. אנרגיה טבעית ללא קפאין. 90 כמוסות.",
    price: 110.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/QGE_MAIN_2d1ddcb7-ea2a-4900-9b09-88224abfceea.jpg",
    category: "Energy & Fitness",
    stock: 90,
  },
  // ── Women's Health ───────────────────────────────────────────────────────────
  {
    name: "Maxi Health One Prenatal™",
    slug: "maxi-health-one-prenatal",
    description: "Comprehensive prenatal multivitamin with folate, iron, DHA, and essential nutrients for expectant mothers and fetal development. 90 capsules.",
    descriptionHe: "מולטי-ויטמין לפני לידה עם פולאט, ברזל, DHA וחומרים מזינים חיוניים לאמהות בהריון ולהתפתחות העובר. 90 כמוסות.",
    price: 96.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/MOP_MAIN_23e05b0d-1da3-4a4d-93b8-46d5bc9066ff.jpg",
    category: "Women's Health",
    stock: 100,
  },
  {
    name: "Maxi Biotin 5000™",
    slug: "maxi-biotin-5000",
    description: "5000mcg biotin to support healthy hair, skin, and nails. Promotes keratin production and cellular energy metabolism. 90 capsules.",
    descriptionHe: "5000 מק\"ג ביוטין לתמיכה בשיער, עור וציפורניים בריאים. מקדם ייצור קרטין ומטבוליזם אנרגיה תאי. 90 כמוסות.",
    price: 82.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/BI_MAIN_3ecb6056-6375-4daa-bc85-53942aca7562.jpg",
    category: "Women's Health",
    stock: 150,
  },
  // ── Immune & Allergy ─────────────────────────────────────────────────────────
  {
    name: "Maxi Allergy Support™",
    slug: "maxi-allergy-support",
    description: "Natural quercetin, bromelain, and vitamin C formula to ease seasonal allergy symptoms and support immune resilience. 90 capsules.",
    descriptionHe: "פורמולה טבעית עם קוורצטין, ברומלין וויטמין C להקלה על תסמיני אלרגיה עונתית וחיזוק החיסון. 90 כמוסות.",
    price: 96.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/A9_MAIN_9685cfab-4ca7-4bd9-86ee-ab28057fa0d1.jpg",
    category: "Immune & Allergy",
    stock: 110,
  },
  {
    name: "Bilberry Supreme™",
    slug: "bilberry-supreme",
    description: "High-potency bilberry extract standardized for anthocyanosides. Supports vision, eye health, and circulation. 90 capsules.",
    descriptionHe: "תמצית אוכמניות בעוצמה גבוהה מתוקננת לאנתוציאנוסידים. תומך בראייה, בריאות העיניים ובמחזור הדם. 90 כמוסות.",
    price: 129.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/QBIL_MAIN_83384c0b-0f5d-42e8-9357-c0d346157ae9.jpg",
    category: "Immune & Allergy",
    stock: 80,
  },
  // ── Children ─────────────────────────────────────────────────────────────────
  {
    name: "Kiddie Boost™",
    slug: "kiddie-boost",
    description: "Immune support formula specially designed for children. Contains elderberry, vitamin C, and zinc in a chewable tablet. 90 chewables.",
    descriptionHe: "פורמולה לחיזוק החיסון שתוכננה במיוחד לילדים. מכילה סמבוק, ויטמין C ואבץ בטבליה לעיסה. 90 לעיסות.",
    price: 135.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/KB_MAIN_a94c5c49-e432-4ca5-b8c7-9a0c814e7330.jpg",
    category: "Children",
    stock: 120,
  },
  {
    name: "Yummie C 250™",
    slug: "yummie-c-250",
    description: "Children's 250mg chewable Vitamin C with a delicious natural flavor. Supports immune health in a fun, kid-friendly way. 90 chewables.",
    descriptionHe: "250 מ\"ג ויטמין C לעיסה לילדים בטעם טבעי טעים. תומך בבריאות החיסון בדרך כיפית ומתאימה לילדים. 90 לעיסות.",
    price: 71.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/YCC9_MAIN_b65edc7e-131e-4a6d-b1e4-2c6832975d86.jpg",
    category: "Children",
    stock: 180,
  },
  {
    name: "Panto C Powder™",
    slug: "panto-c-powder",
    description: "Gentle buffered Vitamin C powder for infants and young children. Mix into food or drink. Corn-free, Gluten-free formula.",
    descriptionHe: "אבקת ויטמין C מאוחזרת ועדינה לתינוקות וילדים קטנים. ניתן לערבב לאוכל או שתייה. ללא תירס, ללא גלוטן.",
    price: 80.90,
    imageUrl: "https://cdn.shopify.com/s/files/1/0728/1449/3948/files/PCP_Main.png",
    category: "Children",
    stock: 140,
  },
];

async function main() {
  console.log("Seeding database...");
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }
  console.log(`Seeded ${products.length} products.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
